"""A SYNTHETIC structure backend. THIS IS NOT STRUCTURE PREDICTION.

Read this before using anything it produces.

What it is: a deterministic function from a sequence to a plausible-looking set
of coordinates. It exists so the rest of the harness — the grounder, the policy
interpreter, the keep-if-better loop, the counterexample recorder, the UI, the
replay-mode cache assertion — can be exercised and verified end to end on a
machine where the 2.6 GB ESMFold checkpoint has not finished downloading.

What it is NOT: a model of protein folding. It has no learned parameters, no
physics, and no relationship to what any of these sequences actually do. Every
TM-score, contact recovery and pLDDT computed from its output is therefore
meaningless as a scientific quantity. It is a harness fixture, nothing else.

Guardrails, so no number from here can be mistaken for a result:
  * every structure it writes carries the REMARK line `SYNTHETIC_REMARK` below;
  * `fold_cache.FoldResult.synthetic` is True for anything carrying that remark;
  * scripts/research/run_demo.py prints a banner and the UI shows a warning badge;
  * `data/cache/` entries written by this backend are indistinguishable from
    ESMFold ones ONLY in file format, never in labelling — clear the cache before
    a real run (`python scripts/clear_synthetic_cache.py`).

Enable with REFOLD_FOLD_BACKEND=synthetic. The default is esmfold.
"""

from __future__ import annotations

import hashlib
import math

import numpy as np

from ..constants import HYDROPHOBIC, THREE_TO_ONE

SYNTHETIC_REMARK = "REMARK   1 SYNTHETIC_GEOMETRY NOT_A_STRUCTURE_PREDICTION"

ONE_TO_THREE = {one: three for three, one in THREE_TO_ONE.items()}

# Template geometry: two antiparallel helices packed side by side. Fixed and
# sequence-independent, so the sequence only ever perturbs it.
HELIX_RADIUS = 2.3
HELIX_RISE = 1.5
HELIX_TURN_DEG = 100.0
PACKING_GAP = 10.5
PERTURBATION_SCALE = 0.9


def _rng(sequence: str) -> np.random.Generator:
    """A generator seeded by the sequence, so folding is deterministic."""
    digest = hashlib.sha256(sequence.encode()).digest()
    return np.random.default_rng(int.from_bytes(digest[:8], "big"))


def _template(n: int) -> tuple[np.ndarray, np.ndarray]:
    def helix(count: int):
        ca, radial = [], []
        for i in range(count):
            theta = math.radians(HELIX_TURN_DEG) * i
            ca.append(
                [
                    HELIX_RADIUS * math.cos(theta),
                    HELIX_RADIUS * math.sin(theta),
                    HELIX_RISE * i,
                ]
            )
            radial.append([math.cos(theta), math.sin(theta), 0.0])
        return np.array(ca), np.array(radial)

    half = n // 2
    ca1, rad1 = helix(half)
    ca2, rad2 = helix(n - half)
    flip = np.array([1.0, 1.0, -1.0])
    offset = np.array([PACKING_GAP, 0.0, float(ca1[-1, 2]) if half else 0.0])
    ca = np.vstack([ca1, ca2 * flip + offset])
    radial = np.vstack([rad1, rad2 * flip])
    return ca, radial


def _burial_preference(sequence: str) -> np.ndarray:
    """Per-residue score in 0-1: how much this residue "wants" to be packed.

    A crude hydrophobicity-in-context heuristic over a 5-residue window. It is
    the only place the sequence influences the geometry, and it is a heuristic,
    not a learned function.
    """
    n = len(sequence)
    scores = np.zeros(n)
    for i in range(n):
        window = sequence[max(0, i - 2) : min(n, i + 3)]
        hydrophobic = sum(1 for aa in window if aa in HYDROPHOBIC)
        scores[i] = hydrophobic / max(len(window), 1)
    return scores


def predict(sequence: str) -> str:
    """Return a PDB string for `sequence`. Deterministic. NOT a prediction."""
    n = len(sequence)
    if n < 4:
        raise ValueError("sequence too short for the synthetic template")

    rng = _rng(sequence)
    ca, radial = _template(n)
    burial = _burial_preference(sequence)

    # Hydrophobic stretches pull inward toward the packing axis; polar ones push
    # out. Plus a small sequence-seeded jitter so distinct sequences differ.
    pull = (burial - 0.5)[:, None] * np.array([[1.0, 0.0, 0.0]]) * 2.0
    pull[n // 2 :] *= -1.0
    jitter = rng.normal(scale=PERTURBATION_SCALE, size=(n, 3))
    ca = ca + pull + jitter

    cb = ca + 1.5 * radial

    # pLDDT stand-in: confident where the local window is consistently packed,
    # less so at termini and in mixed regions. Written on the 0-100 scale that
    # ESMFold uses, so downstream scale detection is exercised too.
    plddt = 55.0 + 40.0 * burial
    plddt[:2] -= 18.0
    plddt[-2:] -= 18.0
    plddt = np.clip(plddt + rng.normal(scale=3.0, size=n), 20.0, 96.0)

    lines = [
        SYNTHETIC_REMARK,
        "REMARK   1 Generated by src/cache/synthetic_backend.py for harness",
        "REMARK   1 integration testing only. Any TM-score, contact recovery or",
        "REMARK   1 pLDDT derived from this file is meaningless.",
    ]
    serial = 1
    for i, aa in enumerate(sequence):
        resname = ONE_TO_THREE[aa]
        atoms = [
            ("N", ca[i] + np.array([-1.20, 0.0, -0.40])),
            ("CA", ca[i]),
            ("C", ca[i] + np.array([1.20, 0.0, 0.40])),
            ("O", ca[i] + np.array([1.80, 0.85, 0.60])),
        ]
        if aa != "G":
            atoms.append(("CB", cb[i]))
        for name, xyz in atoms:
            lines.append(
                "ATOM  "
                f"{serial:5d}"
                " "
                f"{name:<4s}"
                " "
                f"{resname:>3s}"
                " A"
                f"{i + 1:4d}"
                "    "
                f"{xyz[0]:8.3f}{xyz[1]:8.3f}{xyz[2]:8.3f}"
                "  1.00"
                f"{plddt[i]:6.2f}"
            )
            serial += 1
    lines += ["TER", "END"]
    return "\n".join(lines) + "\n"


def is_synthetic(pdb_text: str) -> bool:
    return "SYNTHETIC_GEOMETRY" in pdb_text
