/* ReFold static replay demo.
 *
 * Everything rendered here comes from data/demo.json, which is generated by
 * scripts/build_web_data.py from artefacts committed to the repository. This
 * file adds no numbers of its own — if a value is absent from the bundle it is
 * rendered as "not recorded" rather than filled in.
 */

'use strict';

const STAGE_COLOUR = {
  corrupted: '#f87171',
  baseline:  '#5eb0ef',
  patched:   '#a78bfa',
  native:    '#4ade80',
};

const STAGE_ORDER = ['corrupted', 'baseline', 'patched'];

const state = {
  data: null,
  stage: 'corrupted',
  metricStage: 'corrupted',
  reveal: false,
  viewer: null,
  pdbCache: new Map(),
};

const $ = (id) => document.getElementById(id);
const fmt = (v, d = 4) => (v === null || v === undefined ? '—' : Number(v).toFixed(d));

/* ------------------------------------------------------------------ boot */

async function boot() {
  let data;
  try {
    const res = await fetch('data/demo.json');
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    data = await res.json();
  } catch (err) {
    document.querySelector('.wrap').insertAdjacentHTML(
      'afterbegin',
      `<div class="notice"><h2>Could not load demo data</h2><p>${String(err)}</p>
       <p>Run <code>python scripts/build_web_data.py</code> to regenerate
       <code>web/data/demo.json</code>.</p></div>`
    );
    return;
  }

  state.data = data;
  renderBadges();
  renderSequences();
  renderCorruptTable();
  renderViewerControls();
  renderMetricTabs();
  renderMetrics();
  renderPlddt();
  renderPolicies();
  renderQuote();
  renderScoreBars();
  initViewer();
}

/* ------------------------------------------------------------------ hero */

function renderBadges() {
  const d = state.data;
  const rec = d.recorded;
  const items = [
    `<b>${d.protein}</b> · ${d.native.length} residues`,
    `<b>${d.corruptions.length}</b> point corruptions`,
    `hidden score <b>${fmt(rec.hidden_score.corrupted, 4)}</b> → <b>${fmt(rec.hidden_score.patched, 4)}</b>`,
    `policy reviser <b>${rec.model_policy_reviser}</b>`,
    `recorded <b>${rec.date}</b>`,
  ];
  $('heroBadges').innerHTML = items.map((t) => `<span class="badge">${t}</span>`).join('');
  $('runDate').textContent = rec.date;
}

/* ------------------------------------------------------------------ sequences */

function renderSequences() {
  const d = state.data;
  const native = d.native.sequence;
  const corrupt = d.stages.corrupted.sequence;
  const repaired = d.stages.patched.sequence;

  const corruptedIdx = new Set(d.corruptions.map((c) => c.position));
  const repairIdx = new Set();
  for (let i = 0; i < repaired.length; i++) {
    if (repaired[i] !== corrupt[i]) repairIdx.add(i);
  }

  const track = (seq, classer, extraClass = '') =>
    [...seq]
      .map((aa, i) => {
        const cls = classer(i);
        return `<span class="res ${cls} ${extraClass}" data-pos="${aa}${i + 1}">${aa}</span>`;
      })
      .join('');

  $('seqNative').innerHTML = track(native, (i) => (corruptedIdx.has(i) ? 'ref' : ''), 'ref');
  $('seqCorrupt').innerHTML = track(corrupt, (i) => (corruptedIdx.has(i) ? 'bad' : ''));
  $('seqRepaired').innerHTML = track(repaired, (i) =>
    repairIdx.has(i) ? 'good' : corruptedIdx.has(i) ? 'bad' : ''
  );
}

function renderCorruptTable() {
  const rows = state.data.corruptions
    .map(
      (c) => `<tr>
        <td class="pos">${c.position + 1}</td>
        <td><span class="from">${c.from}</span></td>
        <td><span class="to">${c.to}</span></td>
        <td>${c.rsa.toFixed(4)}</td>
        <td>${c.buried ? 'yes' : 'no'}</td>
      </tr>`
    )
    .join('');
  $('corruptTable').querySelector('tbody').innerHTML = rows;
}

/* ------------------------------------------------------------------ viewer */

function renderViewerControls() {
  const d = state.data;
  $('viewerControls').innerHTML = STAGE_ORDER.map(
    (k) =>
      `<button class="vbtn" data-stage="${k}" aria-pressed="${k === state.stage}">
         ${d.stages[k].label}
       </button>`
  ).join('');

  $('viewerControls').addEventListener('click', (e) => {
    const btn = e.target.closest('.vbtn');
    if (!btn) return;
    state.stage = btn.dataset.stage;
    state.metricStage = btn.dataset.stage;
    [...$('viewerControls').children].forEach((b) =>
      b.setAttribute('aria-pressed', String(b.dataset.stage === state.stage))
    );
    syncMetricTabs();
    renderMetrics();
    drawViewer();
  });

  $('revealToggle').addEventListener('change', (e) => {
    state.reveal = e.target.checked;
    drawViewer();
  });
}

async function fetchPdb(path) {
  if (state.pdbCache.has(path)) return state.pdbCache.get(path);
  const res = await fetch(path);
  if (!res.ok) throw new Error(`could not load ${path}`);
  const text = await res.text();
  state.pdbCache.set(path, text);
  return text;
}

function initViewer() {
  if (typeof $3Dmol === 'undefined') {
    $('viewer').innerHTML =
      '<div class="viewer-fallback">The 3D viewer library could not be loaded.' +
      '<br />The structures are still in the repository under ' +
      '<code>web/data/structures/</code>.</div>';
    return;
  }
  const isLight = window.matchMedia('(prefers-color-scheme: light)').matches;
  state.viewer = $3Dmol.createViewer($('viewer'), {
    backgroundColor: isLight ? '#eef2f8' : '#090b0f',
  });
  drawViewer();
}

async function drawViewer() {
  const v = state.viewer;
  if (!v) return;
  const d = state.data;

  const models = [{ key: state.stage, path: d.stages[state.stage].structure, label: d.stages[state.stage].label }];
  // With the toggle off the reference is never fetched — it cannot reach the
  // DOM by accident. Mirrors build_viewer_models() in app/streamlit_app.py.
  if (state.reveal) {
    models.push({ key: 'native', path: d.native.structure, label: 'reference crystal structure (revealed)' });
  }

  let texts;
  try {
    texts = await Promise.all(models.map((m) => fetchPdb(m.path)));
  } catch (err) {
    $('viewer').innerHTML = `<div class="viewer-fallback">${String(err)}</div>`;
    return;
  }

  v.clear();
  texts.forEach((text, i) => {
    v.addModel(text, 'pdb');
    v.setStyle({ model: i }, { cartoon: { color: STAGE_COLOUR[models[i].key], thickness: 0.9 } });
  });

  // Highlight the corrupted sites on the non-reference model.
  const sites = d.corruptions.map((c) => c.position + 1);
  v.addStyle(
    { model: 0, resi: sites },
    { stick: { radius: 0.18, color: '#fbbf24' }, sphere: { radius: 0.42, color: '#fbbf24' } }
  );

  v.zoomTo();
  v.render();

  $('viewerLegend').innerHTML =
    models
      .map((m) => `<span><i style="background:${STAGE_COLOUR[m.key]}"></i>${m.label}</span>`)
      .join('') + `<span><i style="background:#fbbf24"></i>corrupted sites</span>`;
}

/* ------------------------------------------------------------------ metrics */

function renderMetricTabs() {
  $('metricTabs').innerHTML = STAGE_ORDER.map(
    (k) => `<button class="mtab" data-stage="${k}" aria-pressed="${k === state.metricStage}">${k}</button>`
  ).join('');
  $('metricTabs').addEventListener('click', (e) => {
    const btn = e.target.closest('.mtab');
    if (!btn) return;
    state.metricStage = btn.dataset.stage;
    state.stage = btn.dataset.stage;
    [...$('viewerControls').children].forEach((b) =>
      b.setAttribute('aria-pressed', String(b.dataset.stage === state.stage))
    );
    syncMetricTabs();
    renderMetrics();
    drawViewer();
  });
}

function syncMetricTabs() {
  [...$('metricTabs').children].forEach((b) =>
    b.setAttribute('aria-pressed', String(b.dataset.stage === state.metricStage))
  );
}

function renderMetrics() {
  const d = state.data;
  const key = state.metricStage;
  const m = d.stages[key].computed;
  const base = d.stages.corrupted.computed;

  // `invert` marks metrics where lower is better (clashes). `digits` keeps
  // integer counts from rendering as "-2.0000".
  const delta = (now, was, { invert = false, digits = 4 } = {}) => {
    if (key === 'corrupted') return '';
    const diff = now - was;
    if (Math.abs(diff) < 5e-5) return '';
    const good = invert ? diff < 0 : diff > 0;
    const sign = diff > 0 ? '+' : '';
    return `<span class="delta ${good ? 'up' : 'down'}">${sign}${diff.toFixed(digits)}</span>`;
  };

  const rows = [
    ['TM-score', fmt(m.tm_score), delta(m.tm_score, base.tm_score)],
    ['Contact recovery', fmt(m.contact_recovery), delta(m.contact_recovery, base.contact_recovery)],
    ['Sequence recovery', fmt(m.sequence_recovery), delta(m.sequence_recovery, base.sequence_recovery)],
    ['Mean pLDDT', fmt(m.mean_plddt), delta(m.mean_plddt, base.mean_plddt)],
    ['Steric clashes', String(m.clashes), delta(m.clashes, base.clashes, { invert: true, digits: 0 })],
    ['Radius of gyration', `${m.radius_of_gyration.toFixed(2)} Å`, ''],
    ['Edits vs corrupted', String(m.edit_count), ''],
  ];

  $('metrics').innerHTML = rows
    .map(([k, v, dl]) => `<div><dt>${k}</dt><dd>${v}${dl}</dd></div>`)
    .join('');

  const hs = d.stages[key].recorded_hidden_score;
  const hsBase = d.stages.corrupted.recorded_hidden_score;
  const hsDelta =
    key === 'corrupted'
      ? ''
      : `<span class="delta ${hs > hsBase ? 'up' : 'down'}">${hs > hsBase ? '+' : ''}${(hs - hsBase).toFixed(4)} vs corrupted</span>`;

  $('hiddenScore').innerHTML = `
    <div class="hs-label"><span class="tag tag-recorded">recorded</span> hidden score — the one scalar the agent is told</div>
    <div class="hs-value">${fmt(hs, 4)} ${hsDelta}</div>
    <div class="hs-sub">0.55·TM + 0.20·ESM + 0.15·pLDDT + 0.10·contacts − 0.05·edits.
      The ESM term needs the model, so this composite is carried from the
      ${d.recorded.date} run rather than recomputed.</div>`;
}

/* ------------------------------------------------------------------ pLDDT */

function renderPlddt() {
  const d = state.data;
  const n = d.native.length;
  const W = 900, H = 210, PL = 44, PR = 14, PT = 14, PB = 30;
  const iw = W - PL - PR, ih = H - PT - PB;

  const x = (i) => PL + (i / (n - 1)) * iw;
  const y = (v) => PT + (1 - v) * ih;

  const line = (vals) =>
    vals.map((v, i) => `${i === 0 ? 'M' : 'L'}${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(' ');

  const grid = [0, 0.25, 0.5, 0.75, 1]
    .map(
      (t) =>
        `<line x1="${PL}" y1="${y(t)}" x2="${W - PR}" y2="${y(t)}" stroke="currentColor" stroke-opacity="0.13" />
         <text x="${PL - 8}" y="${y(t) + 4}" text-anchor="end" font-size="11" fill="currentColor" fill-opacity="0.5">${t.toFixed(2)}</text>`
    )
    .join('');

  const ticks = [1, 10, 20, 30, 40, 50, n]
    .map(
      (p) =>
        `<text x="${x(p - 1)}" y="${H - 9}" text-anchor="middle" font-size="11" fill="currentColor" fill-opacity="0.5">${p}</text>`
    )
    .join('');

  const marks = d.corruptions
    .map(
      (c) =>
        `<line x1="${x(c.position)}" y1="${PT}" x2="${x(c.position)}" y2="${PT + ih}"
               stroke="#fbbf24" stroke-opacity="0.34" stroke-dasharray="3 3" />`
    )
    .join('');

  const paths = STAGE_ORDER.map(
    (k) =>
      `<path d="${line(d.stages[k].computed.plddt_per_residue)}" fill="none"
             stroke="${STAGE_COLOUR[k]}" stroke-width="1.9" stroke-linejoin="round" />`
  ).join('');

  const legend = STAGE_ORDER.map(
    (k, i) =>
      `<g transform="translate(${PL + i * 190}, ${PT - 2})">
         <rect width="11" height="11" rx="2" fill="${STAGE_COLOUR[k]}" />
         <text x="16" y="10" font-size="11.5" fill="currentColor" fill-opacity="0.72">${d.stages[k].label}</text>
       </g>`
  ).join('');

  // Described from the series rather than asserted, so the sentence cannot drift
  // away from the data if the bundle is regenerated.
  const mean = (a) => a.reduce((s, v) => s + v, 0) / a.length;
  const cor = d.stages.corrupted.computed.plddt_per_residue;
  const pat = d.stages.patched.computed.plddt_per_residue;
  const argmin = (a) => a.indexOf(Math.min(...a));
  const worstGapRegion = () => {
    const thirds = [[0, 19], [20, 39], [40, n - 1]];
    const gaps = thirds.map(([a, b]) => mean(pat.slice(a, b + 1)) - mean(cor.slice(a, b + 1)));
    const names = ['N-terminal third', 'middle third', 'C-terminal third'];
    const best = gaps.indexOf(Math.max(...gaps));
    return { name: names[best], gap: gaps[best] };
  };
  const wg = worstGapRegion();

  $('plddtChart').innerHTML = `
    <svg viewBox="0 0 ${W} ${H + 26}" role="img"
         aria-label="Per-residue pLDDT for the corrupted input and both repairs">
      <g transform="translate(0,26)" color="var(--ink)">
        ${grid}${marks}${paths}${ticks}
      </g>
      <g color="var(--ink)">${legend}</g>
    </svg>
    <p class="metrics-note" style="margin-top:10px">
      Dashed gold lines mark the five corrupted positions. The corrupted input is
      depressed along the entire chain — mean ${mean(cor).toFixed(2)}, bottoming out at
      ${Math.min(...cor).toFixed(2)} near residue ${argmin(cor) + 1} — while both repairs sit
      near ${mean(pat).toFixed(2)}. A single substitution at position 50 lifts confidence
      everywhere, most of all across the ${wg.name} (+${wg.gap.toFixed(2)}).
    </p>`;
}

/* ------------------------------------------------------------------ policy */

function policyYaml(policy, reference) {
  const ps = policy.position_score;
  const pr = policy.proposal;
  const cmp = reference ? reference.proposal : null;

  const line = (k, v, changedFrom) => {
    const isChanged = changedFrom !== undefined && changedFrom !== null && changedFrom !== v;
    if (v === null) {
      return `  <span class="k">${k}</span>: <span class="unknown" title="Known to have increased from Gemma's own rationale, but the exact value lived only in logs/, which is gitignored.">increased (not recorded)</span>`;
    }
    const val = `<span class="v">${v}</span>`;
    return `  <span class="k">${k}</span>: ${isChanged ? `<span class="changed">${val}</span>` : val}`;
  };

  const psLines = Object.keys(ps).sort().map((k) => line(k, ps[k])).join('\n');
  const prLines = Object.keys(pr)
    .sort()
    .map((k) => line(k, pr[k], cmp ? cmp[k] : undefined))
    .join('\n');

  return `<span class="k">position_score</span>:\n${psLines}\n<span class="k">proposal</span>:\n${prLines}`;
}

function renderPolicies() {
  const d = state.data;
  const seed = d.policy.seed;
  const patched = d.policy.patched;

  $('seedPolicy').innerHTML = policyYaml(seed, null);
  $('patchedPolicy').innerHTML = policyYaml(patched, seed);

  const rec = d.recorded;
  const facts = (which) => {
    const sites = rec.sites_1based[which];
    return `
      <li><span>sites selected</span><b>[${sites.join(', ')}]</b></li>
      <li><span>mutations proposed</span><b>${rec.proposals[which]}</b></li>
      <li><span>picked</span><b>${rec.picked[which]}</b></li>
      <li><span>hidden score</span><b>${fmt(rec.hidden_score[which], 4)}</b></li>`;
  };
  $('baselineFacts').innerHTML = facts('baseline');
  $('patchedFacts').innerHTML = facts('patched');
}

function renderQuote() {
  const rec = state.data.recorded;
  $('gemmaQuote').innerHTML = `
    “${rec.gemma_rationale}”
    <span class="attrib">— ${rec.model_policy_reviser}, explaining its own patch ·
      <span class="tag tag-recorded" style="margin-left:4px">recorded</span> ${rec.date}</span>`;
}

/* ------------------------------------------------------------------ bars */

function renderScoreBars() {
  const d = state.data;
  const rec = d.recorded;

  const rows = [
    ['corrupted input', rec.hidden_score.corrupted, STAGE_COLOUR.corrupted],
    [`baseline (${rec.picked.baseline})`, rec.hidden_score.baseline, STAGE_COLOUR.baseline],
    [`patched (${rec.picked.patched})`, rec.hidden_score.patched, STAGE_COLOUR.patched],
  ];

  const bars = rows
    .map(
      ([name, val, colour]) => `
      <div class="bar-row">
        <div class="bar-name">${name}</div>
        <div class="bar-track"><div class="bar-fill" style="width:${(val * 100).toFixed(1)}%;background:${colour}"></div></div>
        <div class="bar-val">${fmt(val, 4)}</div>
      </div>`
    )
    .join('');

  $('scoreBars').innerHTML = `
    <h3>Hidden score across the run <span class="tag tag-recorded">recorded</span></h3>
    ${bars}
    <p class="metrics-note" style="margin-top:14px">
      The +0.233 jump comes from reverting the proline at position 50. ESM-2 flagged
      it as the most implausible residue in the chain without ever seeing the
      reference structure. Gemma's patch then added +0.005 on top by widening the
      search to five sites.
    </p>`;
}

document.addEventListener('DOMContentLoaded', boot);
